/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.doctor;

import dao.*;
import model.*;
import services.*;
import session.UserSession;
import util.DateUtil;
import util.ValidationUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author pranjalpatil
 */
public class CreateDiagnosisPanel extends javax.swing.JPanel {

    private DoctorService doctorService;
    private AssessmentDAO assessmentDAO;
    private ComplaintDAO complaintDAO;
    private PatientDAO patientDAO;
    private int assessmentID;
    private Assessment currentAssessment;

    public CreateDiagnosisPanel(int assessmentID) {
        this.assessmentID = assessmentID;
        initComponents();

        this.doctorService = new DoctorService();
        this.assessmentDAO = new AssessmentDAO();
        this.complaintDAO = new ComplaintDAO();
        this.patientDAO = new PatientDAO();

        loadAssessmentInfo();
    }

    // Load assessment information
    private void loadAssessmentInfo() {
        try {
            // Get assessment
            currentAssessment = assessmentDAO.getAssessmentByID(assessmentID);

            if (currentAssessment == null) {
                JOptionPane.showMessageDialog(this, "Assessment not found", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Get complaint
            Complaint complaint = complaintDAO.getComplaintByID(currentAssessment.getComplaintID());

            if (complaint != null) {
                fieldComplaint.setText("C" + complaint.getComplaintID());
                fieldComplaint.setEditable(false);

                // Get patient
                Patient patient = patientDAO.getPatientByID(complaint.getPatientID());

                if (patient != null) {
                    fieldPatient.setText(patient.getFullName());
                    fieldPatient.setEditable(false);
                }
            }

            // Set date
            fieldDate.setText(DateUtil.getCurrentDate());
            fieldDate.setEditable(false);

            // Set assessment summary
            fieldAssesment.setText(currentAssessment.getSymptoms());
            fieldAssesment.setEditable(false);

        } catch (Exception e) {
            System.err.println("Error loading assessment: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Get selected severity
    private String getSelectedSeverity() {
        if (cbMild.isSelected()) {
            return "MILD";
        }
        if (cbModerate.isSelected()) {
            return "MODERATE";
        }
        if (cbSevere.isSelected()) {
            return "SEVERE";
        }
        if (cbLifeThreat.isSelected()) {
            return "LIFE_THREATENING";
        }
        return "";
    }

    // Ensure only one severity checkbox is selected
    private void updateSeverityCheckboxes(javax.swing.JCheckBox selected) {
        cbMild.setSelected(false);
        cbModerate.setSelected(false);
        cbSevere.setSelected(false);
        cbLifeThreat.setSelected(false);
        selected.setSelected(true);
    }

    // Navigate back to dashboard
    private void navigateBackToDashboard() {
        try {
            java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

            if (window instanceof javax.swing.JFrame) {
                javax.swing.JFrame frame = (javax.swing.JFrame) window;
                frame.getContentPane().removeAll();
                frame.getContentPane().add(new DoctorDashboard());
                frame.revalidate();
                frame.repaint();
            }

        } catch (Exception e) {
            System.err.println("Error navigating back: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldPatient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldComplaint = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldAssesment = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldDiagnosisCode = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        fieldDiagnosisName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbMild = new javax.swing.JCheckBox();
        cbModerate = new javax.swing.JCheckBox();
        cbSevere = new javax.swing.JCheckBox();
        cbLifeThreat = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDescription = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldTreatment = new javax.swing.JTextArea();
        cbRequirement = new javax.swing.JCheckBox();
        combobxSpeciality = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnSaveDiagnosis = new javax.swing.JButton();
        btnCreateTreatment = new javax.swing.JButton();
        btnReferSpeac = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 244, 248));

        jPanel3.setBackground(new java.awt.Color(13, 115, 119));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 244, 248));
        jLabel1.setText("MEDIRESOLVE");

        jLabel2.setForeground(new java.awt.Color(232, 244, 248));
        jLabel2.setText("Create Diagnosis");

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(13, 115, 119));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnBack))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(13, 115, 119));
        jLabel7.setText("ASSESMENT SUMMARY");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 115, 119));
        jLabel3.setText("PATIENT");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(13, 115, 119));
        jLabel4.setText("COMPLAINT");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(13, 115, 119));
        jLabel5.setText("DATE");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(13, 115, 119));
        jLabel6.setText("ASSESMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(fieldDate))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldComplaint, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(fieldAssesment)))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(fieldComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(fieldAssesment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(13, 115, 119));
        jLabel8.setText("DIAGNOSIS");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(13, 115, 119));
        jLabel9.setText("DIAGNOSIS CODE");

        btnSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(13, 115, 119));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(13, 115, 119));
        jLabel10.setText("DIAGNOSIS NAME");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(13, 115, 119));
        jLabel11.setText("SEVERITY");

        cbMild.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cbMild.setForeground(new java.awt.Color(13, 115, 119));
        cbMild.setText("MILD");
        cbMild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMildActionPerformed(evt);
            }
        });

        cbModerate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cbModerate.setForeground(new java.awt.Color(13, 115, 119));
        cbModerate.setText("MODERATE");
        cbModerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModerateActionPerformed(evt);
            }
        });

        cbSevere.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cbSevere.setForeground(new java.awt.Color(13, 115, 119));
        cbSevere.setText("SEVERE");
        cbSevere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSevereActionPerformed(evt);
            }
        });

        cbLifeThreat.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cbLifeThreat.setForeground(new java.awt.Color(13, 115, 119));
        cbLifeThreat.setText("LIFE THREATNING");
        cbLifeThreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLifeThreatActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(13, 115, 119));
        jLabel12.setText("DESCRIPTION");

        fieldDescription.setColumns(20);
        fieldDescription.setForeground(new java.awt.Color(13, 115, 119));
        fieldDescription.setRows(5);
        jScrollPane1.setViewportView(fieldDescription);

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(13, 115, 119));
        jLabel13.setText("TREATMENT RECOMMENDATION");

        fieldTreatment.setColumns(20);
        fieldTreatment.setForeground(new java.awt.Color(13, 115, 119));
        fieldTreatment.setRows(5);
        jScrollPane2.setViewportView(fieldTreatment);

        cbRequirement.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cbRequirement.setForeground(new java.awt.Color(13, 115, 119));
        cbRequirement.setText("Requires Specialist Consultation");

        combobxSpeciality.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        combobxSpeciality.setForeground(new java.awt.Color(13, 115, 119));
        combobxSpeciality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology (Heart & Cardiovascular)", "Pulmonology (Lungs & Respiratory)", "Neurology (Brain & Nervous System)", "Orthopedics (Bones & Joints)", "Gastroenterology (Digestive System)", "Endocrinology (Hormones & Metabolism)", "Nephrology (Kidneys)", "Oncology (Cancer)", "Dermatology (Skin)", "Psychiatry (Mental Health)", "General Surgery", "Cardiothoracic Surgery", "Neurosurgery", "Orthopedic Surgery", "Plastic Surgery", "Ophthalmology (Eyes)", "ENT (Ear, Nose, Throat)", "Urology (Urinary System)", "Gynecology (Women's Health)", "Pediatrics (Children)", "Geriatrics (Elderly)", "Rheumatology (Autoimmune & Joint disorders)", "Hematology (Blood disorders)", "Infectious Disease", "Emergency Medicine", "Anesthesiology", "Radiology", "Pathology" }));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(13, 115, 119));
        jLabel14.setText("SPECIALITY");

        btnSaveDiagnosis.setBackground(new java.awt.Color(13, 115, 119));
        btnSaveDiagnosis.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSaveDiagnosis.setForeground(new java.awt.Color(232, 244, 248));
        btnSaveDiagnosis.setText("SAVE DIAGNOSIS");
        btnSaveDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDiagnosisActionPerformed(evt);
            }
        });

        btnCreateTreatment.setBackground(new java.awt.Color(13, 115, 119));
        btnCreateTreatment.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCreateTreatment.setForeground(new java.awt.Color(232, 244, 248));
        btnCreateTreatment.setText("CREATE TREATMENT");
        btnCreateTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTreatmentActionPerformed(evt);
            }
        });

        btnReferSpeac.setBackground(new java.awt.Color(13, 115, 119));
        btnReferSpeac.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnReferSpeac.setForeground(new java.awt.Color(232, 244, 248));
        btnReferSpeac.setText("REFER SPECIALIST");
        btnReferSpeac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReferSpeacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldDiagnosisCode, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(btnSearch))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(61, 61, 61)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbMild)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbModerate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbSevere)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbLifeThreat))
                                            .addComponent(fieldDiagnosisName, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbRequirement)
                                        .addGap(163, 163, 163)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(btnSaveDiagnosis)
                                        .addGap(44, 44, 44)
                                        .addComponent(btnCreateTreatment)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(combobxSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnReferSpeac)
                                        .addGap(85, 85, 85)))))
                        .addGap(0, 51, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldDiagnosisCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(fieldDiagnosisName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMild)
                        .addComponent(cbModerate)
                        .addComponent(cbSevere)
                        .addComponent(cbLifeThreat)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRequirement)
                    .addComponent(combobxSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveDiagnosis)
                    .addComponent(btnCreateTreatment)
                    .addComponent(btnReferSpeac))
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        navigateBackToDashboard();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbMildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMildActionPerformed
        updateSeverityCheckboxes(cbMild);
    }//GEN-LAST:event_cbMildActionPerformed

    private void cbModerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModerateActionPerformed
        updateSeverityCheckboxes(cbModerate);
    }//GEN-LAST:event_cbModerateActionPerformed

    private void cbSevereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSevereActionPerformed
        updateSeverityCheckboxes(cbSevere);
    }//GEN-LAST:event_cbSevereActionPerformed

    private void cbLifeThreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLifeThreatActionPerformed
        updateSeverityCheckboxes(cbLifeThreat);
    }//GEN-LAST:event_cbLifeThreatActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        JOptionPane.showMessageDialog(this,
                "ICD Code Search\n\n(Feature not implemented - enter code manually)",
                "Search",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDiagnosisActionPerformed
        String diagnosisCode = fieldDiagnosisCode.getText().trim();
        String diagnosisName = fieldDiagnosisName.getText().trim();
        String description = fieldDescription.getText().trim();
        String severity = getSelectedSeverity();

        if (ValidationUtil.isEmpty(diagnosisName)) {
            JOptionPane.showMessageDialog(this, "Please enter diagnosis name", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (ValidationUtil.isEmpty(severity)) {
            JOptionPane.showMessageDialog(this, "Please select severity", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (ValidationUtil.isEmpty(description)) {
            JOptionPane.showMessageDialog(this, "Please enter description", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Create diagnosis
        Diagnosis diagnosis = doctorService.createDiagnosis(
                assessmentID,
                diagnosisCode,
                diagnosisName,
                description,
                severity
        );

        if (diagnosis != null) {
            JOptionPane.showMessageDialog(this,
                    "Diagnosis saved successfully!\n\nDiagnosis ID: D" + diagnosis.getDiagnosisID(),
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            navigateBackToDashboard();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save diagnosis", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveDiagnosisActionPerformed

    private void btnCreateTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTreatmentActionPerformed
        String diagnosisName = fieldDiagnosisName.getText().trim();
        String description = fieldDescription.getText().trim();
        String severity = getSelectedSeverity();
        String treatmentPlan = fieldTreatment.getText().trim();

        if (ValidationUtil.isEmpty(diagnosisName) || ValidationUtil.isEmpty(severity) || ValidationUtil.isEmpty(description)) {
            JOptionPane.showMessageDialog(this, "Please complete diagnosis information first", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (ValidationUtil.isEmpty(treatmentPlan)) {
            JOptionPane.showMessageDialog(this, "Please enter treatment recommendation", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Create diagnosis
        String diagnosisCode = fieldDiagnosisCode.getText().trim();
        Diagnosis diagnosis = doctorService.createDiagnosis(assessmentID, diagnosisCode, diagnosisName, description, severity);

        if (diagnosis != null) {
            // Create treatment
            Treatment treatment = doctorService.createTreatment(
                    diagnosis.getDiagnosisID(),
                    treatmentPlan,
                    "",
                    "",
                    null
            );

            if (treatment != null) {
                JOptionPane.showMessageDialog(this,
                        "Diagnosis and Treatment created successfully!\n\n"
                        + "Diagnosis ID: D" + diagnosis.getDiagnosisID() + "\n"
                        + "Treatment ID: T" + treatment.getTreatmentID(),
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                navigateBackToDashboard();
            } else {
                JOptionPane.showMessageDialog(this, "Diagnosis saved but treatment creation failed", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save diagnosis", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateTreatmentActionPerformed

    private void btnReferSpeacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReferSpeacActionPerformed
        if (!cbRequirement.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please check 'Requires Specialist Consultation' first", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Validate diagnosis is created
        String diagnosisName = fieldDiagnosisName.getText().trim();
        String description = fieldDescription.getText().trim();
        String severity = getSelectedSeverity();

        if (ValidationUtil.isEmpty(diagnosisName) || ValidationUtil.isEmpty(severity)) {
            JOptionPane.showMessageDialog(this, "Please complete diagnosis information first", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Create diagnosis first
        String diagnosisCode = fieldDiagnosisCode.getText().trim();
        Diagnosis diagnosis = doctorService.createDiagnosis(assessmentID, diagnosisCode, diagnosisName, description, severity);

        if (diagnosis != null) {
            // Navigate to refer specialist panel
            try {
                java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

                if (window instanceof javax.swing.JFrame) {
                    javax.swing.JFrame frame = (javax.swing.JFrame) window;
                    frame.getContentPane().removeAll();
                    frame.getContentPane().add(new ReferSpecialistPanel(diagnosis.getDiagnosisID()));
                    frame.revalidate();
                    frame.repaint();
                }

            } catch (Exception e) {
                System.err.println("Error navigating to referral: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save diagnosis", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReferSpeacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateTreatment;
    private javax.swing.JButton btnReferSpeac;
    private javax.swing.JButton btnSaveDiagnosis;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox cbLifeThreat;
    private javax.swing.JCheckBox cbMild;
    private javax.swing.JCheckBox cbModerate;
    private javax.swing.JCheckBox cbRequirement;
    private javax.swing.JCheckBox cbSevere;
    private javax.swing.JComboBox<String> combobxSpeciality;
    private javax.swing.JTextField fieldAssesment;
    private javax.swing.JTextField fieldComplaint;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextArea fieldDescription;
    private javax.swing.JTextField fieldDiagnosisCode;
    private javax.swing.JTextField fieldDiagnosisName;
    private javax.swing.JTextField fieldPatient;
    private javax.swing.JTextArea fieldTreatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
