/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import services.AuthService;
import model.User;
import model.Patient;
import model.Employee;
import session.UserSession;
import util.ValidationUtil;
import dao.AuditLogDAO;
import model.AuditLog;
import javax.swing.JOptionPane;

/**
 *
 * @author pranjalpatil
 */
public class LoginFrame extends javax.swing.JPanel {

    /**
     * Creates new form LoginFrame
     */
    private AuthService authService;

    public LoginFrame() {
        initComponents();
        authService = new AuthService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        fieldPw = new javax.swing.JTextField();
        fieldUserName = new javax.swing.JTextField();
        btnForgotPw = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(13, 115, 119));

        jPanel2.setBackground(new java.awt.Color(232, 244, 248));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 115, 119));
        jLabel2.setText("PASSWORD:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 115, 119));
        jLabel3.setText("USERNAME:");

        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(13, 115, 119));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(13, 115, 119));
        jLabel4.setText("New Patient?");

        btnRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(13, 115, 119));
        btnRegister.setText("Register");

        btnForgotPw.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnForgotPw.setForeground(new java.awt.Color(13, 115, 119));
        btnForgotPw.setText("Forgot Password");
        btnForgotPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPw, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister)
                            .addComponent(btnLogin)
                            .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnForgotPw)
                        .addGap(126, 126, 126)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldPw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnForgotPw)
                .addGap(88, 88, 88))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 244, 248));
        jLabel1.setText("MEDIRESOLVE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = fieldUserName.getText().trim();
        String password = fieldPw.getText().trim();

        // Validate
        if (ValidationUtil.isEmpty(username)) {
            JOptionPane.showMessageDialog(this, "Please enter username", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (ValidationUtil.isEmpty(password)) {
            JOptionPane.showMessageDialog(this, "Please enter password", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Login
        User user = authService.login(username, password);

        if (user != null) {
            // Success
            JOptionPane.showMessageDialog(this, "Welcome " + user.getUsername() + "!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Create audit log
            createAuditLog(user.getUserID(), "LOGIN", "USER", user.getUserID(), "Login successful", "127.0.0.1");

            // Open dashboard
            openDashboardForRole(user.getRole());

            // Hide login window instead of dispose
            this.setVisible(false);

        } else {
            // Failed
            JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);

            // Create failed login audit log
            createAuditLog(0, "FAILED_LOGIN", "USER", null, "Failed login: " + username, "127.0.0.1");

            fieldPw.setText("");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnForgotPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnForgotPwActionPerformed

    private void openDashboardForRole(String role) {
        switch (role) {
            case "PATIENT":
                // Open patient dashboard when ready
                // new PatientDashboard().setVisible(true);
                JOptionPane.showMessageDialog(this, "Opening Patient Dashboard...");
                break;

            case "DOCTOR":
                // Open doctor dashboard when ready
                // new DoctorDashboard().setVisible(true);
                JOptionPane.showMessageDialog(this, "Opening Doctor Dashboard...");
                break;

            case "SPECIALIST":
                // Open specialist dashboard when ready
                // new SpecialistDashboard().setVisible(true);
                JOptionPane.showMessageDialog(this, "Opening Specialist Dashboard...");
                break;

            case "PHARMACIST":
                // Open pharmacist dashboard when ready
                // new PharmacistDashboard().setVisible(true);
                JOptionPane.showMessageDialog(this, "Opening Pharmacist Dashboard...");
                break;

            case "INSURANCE":
                // Open insurance dashboard when ready
                // new InsuranceDashboard().setVisible(true);
                JOptionPane.showMessageDialog(this, "Opening Insurance Dashboard...");
                break;

            case "RESEARCHER":
                // Open researcher dashboard when ready
                // new ResearcherDashboard().setVisible(true);
                JOptionPane.showMessageDialog(this, "Opening Researcher Dashboard...");
                break;

            case "AUDITOR":
                // Open auditor dashboard
                javax.swing.JFrame frame = new javax.swing.JFrame("Auditor Dashboard");
                frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                frame.add(new ui.auditor.AuditorDashboard());
                frame.setSize(900, 700);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
                break;

            case "ADMIN":
                // Open admin dashboard when ready
                // new AdminDashboard().setVisible(true);
                JOptionPane.showMessageDialog(this, "Opening Admin Dashboard...");
                break;

            default:
                JOptionPane.showMessageDialog(this,
                        "Unknown role: " + role,
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
        }
    }

    private void createAuditLog(int userID, String action, String entityType,
            Integer entityID, String details, String ipAddress) {
        try {
            AuditLogDAO auditLogDAO = new AuditLogDAO();
            AuditLog log = new AuditLog();
            log.setUserID(userID);
            log.setAction(action);
            log.setEntityType(entityType);
            log.setEntityID(entityID);
            log.setDetails(details);
            log.setIpAddress(ipAddress);

            auditLogDAO.createAuditLog(log);
        } catch (Exception e) {
            System.err.println("Failed to create audit log: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgotPw;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField fieldPw;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
